#!/usr/bin/env python3
"""Audit website source and generated output for release-blocking content."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

TEXT_EXTENSIONS = {
    ".md", ".markdown", ".html", ".htm", ".yaml", ".yml", ".json",
    ".scss", ".css", ".js", ".mjs", ".cjs", ".py", ".rb", ".xml",
    ".txt", ".toml",
}

EXCLUDED_DIRECTORIES = {
    ".git", ".jekyll-cache", ".sass-cache", "vendor", "node_modules",
    "__pycache__", ".bundle",
}

BLOCKED_PHRASES = {
    "requested lab portfolio",
    "all projects requested for inclusion",
    "requested project portfolio",
    "supplied by the lab for inclusion",
    "documentation limited",
    "public summary forthcoming",
    "project brief:",
    "no public-facing title",
    "until verified details",
    "unverified technical claims",
    "next-generation benchmarking",
    "for reference only",
    "not intended for public sharing",
    "private slide deck",
    "private reference materials",
    "generated through chatgpt",
    "generated by chatgpt",
    "internal note",
    "implementation note",
    "lorem ipsum",
}

BLOCKED_PATH_FRAGMENTS = {
    "/users/lauren/",
    "/mnt/data/",
    "bukharilabwebsite-backups",
}

HIGH_CONFIDENCE_SECRET_PATTERNS = {
    "private key": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    "github token": re.compile(r"\bgh[pousr]_[A-Za-z0-9]{30,}\b"),
    "aws access key": re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    "slack token": re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{20,}\b"),
}

SENSITIVE_FILENAMES = {
    ".env", ".env.local", ".env.production", "credentials.json",
    "service-account.json", "secrets.yml", "secrets.yaml",
}


def should_skip(path: Path, include_built: bool) -> bool:
    for part in path.parts:
        if part in EXCLUDED_DIRECTORIES:
            return True
        if part == "_site" and not include_built:
            return True
    return False


def iter_text_files(root: Path, include_built: bool):
    for path in root.rglob("*"):
        if not path.is_file() or should_skip(path.relative_to(root), include_built):
            continue
        if path.name == "public_release_audit.py":
            continue
        if path.suffix.lower() in TEXT_EXTENSIONS or path.name in {
            "Gemfile", "Rakefile", "CNAME", "LICENSE", "LICENSE.md", "README",
        }:
            yield path


def audit(root: Path, include_built: bool) -> list[str]:
    findings: list[str] = []

    for path in root.rglob("*"):
        if not path.is_file() or should_skip(path.relative_to(root), include_built):
            continue
        relative = path.relative_to(root)
        lower_name = path.name.lower()

        if lower_name in SENSITIVE_FILENAMES:
            findings.append(f"{relative}: sensitive filename should not be committed")

        if path.suffix.lower() in {".pem", ".key", ".p12", ".pfx"}:
            findings.append(f"{relative}: private credential file type should not be committed")

    for path in iter_text_files(root, include_built):
        relative = path.relative_to(root)
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue

        lowered = text.lower()

        for phrase in sorted(BLOCKED_PHRASES):
            if phrase in lowered:
                findings.append(f"{relative}: contains release-blocking phrase {phrase!r}")

        for fragment in sorted(BLOCKED_PATH_FRAGMENTS):
            if fragment in lowered:
                findings.append(f"{relative}: contains local filesystem path {fragment!r}")

        for label, pattern in HIGH_CONFIDENCE_SECRET_PATTERNS.items():
            if pattern.search(text):
                findings.append(f"{relative}: contains a possible {label}")

        for line_number, line in enumerate(text.splitlines(), start=1):
            if re.search(r"\b(?:TODO|FIXME|XXX)\b", line, flags=re.IGNORECASE):
                findings.append(f"{relative}:{line_number}: contains an unfinished-work marker")

    return sorted(set(findings))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "root",
        nargs="?",
        default=".",
        help="repository root, default: current directory",
    )
    parser.add_argument(
        "--include-built",
        action="store_true",
        help="also scan generated files under _site",
    )
    args = parser.parse_args()

    root = Path(args.root).expanduser().resolve()
    if not root.exists():
        print(f"Audit root does not exist: {root}", file=sys.stderr)
        return 2

    findings = audit(root, args.include_built)
    if findings:
        print("Public-release audit found issues:\n")
        for finding in findings:
            print(f"  - {finding}")
        return 1

    scope = "source and generated output" if args.include_built else "source"
    print(f"Public-release audit passed for {scope}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
